language: java
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ant
jdk:
  - oraclejdk8
env:
  - TEST_DIR=CompetitionTemplate
script: "cd $TEST_DIR && ant check -f robot-program-build.xml"